### ISSUE TITLE
Update the Create a New React.js App chapter to use Vite instead of CRA

### ISSUE THREAD

**Issue by cbnsndwch** [sst/sst.dev#728]
## Description

The `Create a New React.js App` chapter still walks readers through creating a React app with CRA, even though it's been deprecated and the React docs now don't even mention it.

## Suggestion

Replpace the CRA steps with Vite equivalents.

## Willing to contribute

At my startup use Vite for our SPAs running in production and have a stable setup. I'd be happy to open a PR to take care of it.

**Comment by jayair** [comment]
Just rolled out a new version that does this switch: https://github.com/sst/sst.dev/releases/tag/v8.0

**Comment by cbnsndwch** [comment]
Yep, that did the trick. Thanks!
