### ISSUE TITLE
Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

### ISSUE THREAD

**Issue by arifoyong** [sst/sst.dev#733]
When running this code:  ` serverless invoke local --function create --path mocks/create-event.json`
I receive the following error `Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`

I have tried to add access key, secret key, and session token in 3 different ways:
1) set in environment variable by using export
2) Add into ~/.aws/credentials
3) Add directly into my code:
```
const config = {
    apiVersion: "2023-09-13",
    accessKeyId: <my acccess key>,
    accessSecretKey: <my secret key>
    sessionToken: <my session token>
    region: "ap-southeast-1",
    sdkLoadConfig: 1
}
AWS.config.update(config)
```

All 3 options gave me the same error. 
Anyone facing the same issue?

**Comment by jayair** [comment]
Sorry post this over on the Serverless Framework GH instead.
